// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AppLoading: typeof import('./components/Loadings/AppLoading.vue')['default'];
		AppModal: typeof import('./components/Modals/AppModal.vue')['default'];
		AsMenu: typeof import('~icons/as/menu')['default'];
		Bitcoin: typeof import('./components/Apps/Bitcoin.vue')['default'];
		Calender: typeof import('./components/Apps/Calender.vue')['default'];
		ElButton: typeof import('element-plus/es')['ElButton'];
		ElDialog: typeof import('element-plus/es')['ElDialog'];
		ElDropdown: typeof import('element-plus/es')['ElDropdown'];
		ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
		ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
		ElIcon: typeof import('element-plus/es')['ElIcon'];
		ElSwitch: typeof import('element-plus/es')['ElSwitch'];
		EpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default'];
		EpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default'];
		EpClose: typeof import('~icons/ep/close')['default'];
		EpEdit: typeof import('~icons/ep/edit')['default'];
		EpHelpFilled: typeof import('~icons/ep/help-filled')['default'];
		EpHome: typeof import('~icons/ep/home')['default'];
		EpHomeFilled: typeof import('~icons/ep/home-filled')['default'];
		EpMenu: typeof import('~icons/ep/menu')['default'];
		EpMore: typeof import('~icons/ep/more')['default'];
		EpNotification: typeof import('~icons/ep/notification')['default'];
		EpOdometer: typeof import('~icons/ep/odometer')['default'];
		EpPictureRounded: typeof import('~icons/ep/picture-rounded')['default'];
		EpUploadFilled: typeof import('~icons/ep/upload-filled')['default'];
		EpUser: typeof import('~icons/ep/user')['default'];
		Icon: typeof import('./components/Apps/Icon.vue')['default'];
		IEpAddLocation: typeof import('~icons/ep/add-location')['default'];
		IEpEdit: typeof import('~icons/ep/edit')['default'];
		LayoutPieChart: typeof import('./components/Charts/LayoutPieChart.vue')['default'];
		MdiMenu: typeof import('~icons/mdi/menu')['default'];
		News: typeof import('./components/Apps/News.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}
